namespace DomainConstants {
  export class Region {
    static readonly CN_HANGZHOU: string = "cn-hangzhou";
    static readonly CN_SHANGHAI: string = "cn-shanghai";
    static readonly CN_NANJING: string = "cn-nanjing";
    static readonly CN_FUZHOU: string = "cn-fuzhou";
    static readonly CN_WUHAN: string = "cn-wuhan";
    static readonly CN_QINGDAO: string = "cn-qingdao";
    static readonly CN_BEIJING: string = "cn-beijing";
    static readonly CN_ZHANGJIAKOU: string = "cn-zhangjiakou";
    static readonly CN_HUHEHAOTE: string = "cn-huhehaote";
    static readonly CN_WULANCHABU: string = "cn-wulanchabu";
    static readonly CN_SHENZHEN: string = "cn-shenzhen";
    static readonly CN_HEYUAN: string = "cn-heyuan";
    static readonly CN_GUANGZHOU: string = "cn-guangzhou";
    static readonly CN_CHENGDU: string = "cn-chengdu";
    static readonly CN_HONGKONG: string = "cn-hongkong";
    static readonly US_WEST_1: string = "us-west-1";
    static readonly US_EAST_1: string = "us-east-1";
    static readonly AP_NORTHEAST_1: string = "ap-northeast-1";
    static readonly AP_NORTHEAST_2: string = "ap-northeast-2";
    static readonly AP_SOUTHEAST_1: string = "ap-southeast-1";
    static readonly AP_SOUTHEAST_2: string = "ap-southeast-2";
    static readonly AP_SOUTHEAST_3: string = "ap-southeast-3";
    static readonly AP_SOUTHEAST_5: string = "ap-southeast-5";
    static readonly AP_SOUTHEAST_6: string = "ap-southeast-6";
    static readonly AP_SOUTHEAST_7: string = "ap-southeast-7";
    static readonly EU_CENTRAL_1: string = "eu-central-1";
    static readonly EU_WEST_1: string = "eu-west-1";
    static readonly ME_EAST_1: string = "me-east-1";
  }

  export class PublicEndpoint {
    static readonly CN_HANGZHOU: string = "oss-cn-hangzhou.aliyuncs.com";
    static readonly CN_SHANGHAI: string = "oss-cn-shanghai.aliyuncs.com";
    static readonly CN_NANJING: string = "oss-cn-nanjing.aliyuncs.com";
    static readonly CN_FUZHOU: string = "oss-cn-fuzhou.aliyuncs.com";
    static readonly CN_WUHAN: string = "oss-cn-wuhan-lr.aliyuncs.com";
    static readonly CN_QINGDAO: string = "oss-cn-qingdao.aliyuncs.com";
    static readonly CN_BEIJING: string = "oss-cn-beijing.aliyuncs.com";
    static readonly CN_ZHANGJIAKOU: string = "oss-cn-zhangjiakou.aliyuncs.com";
    static readonly CN_HUHEHAOTE: string = "oss-cn-huhehaote.aliyuncs.com";
    static readonly CN_WULANCHABU: string = "oss-cn-wulanchabu.aliyuncs.com";
    static readonly CN_SHENZHEN: string = "oss-cn-shenzhen.aliyuncs.com";
    static readonly CN_HEYUAN: string = "oss-cn-heyuan.aliyuncs.com";
    static readonly CN_GUANGZHOU: string = "oss-cn-guangzhou.aliyuncs.com";
    static readonly CN_CHENGDU: string = "oss-cn-chengdu.aliyuncs.com";
    static readonly CN_HONGKONG: string = "oss-cn-hongkong.aliyuncs.com";
    static readonly US_WEST_1: string = "oss-us-west-1.aliyuncs.com";
    static readonly US_EAST_1: string = "oss-us-east-1.aliyuncs.com";
    static readonly AP_NORTHEAST_1: string = "oss-ap-northeast-1.aliyuncs.com";
    static readonly AP_NORTHEAST_2: string = "oss-ap-northeast-2.aliyuncs.com";
    static readonly AP_SOUTHEAST_1: string = "oss-ap-southeast-1.aliyuncs.com";
    static readonly AP_SOUTHEAST_2: string = "oss-ap-southeast-2.aliyuncs.com";
    static readonly AP_SOUTHEAST_3: string = "oss-ap-southeast-3.aliyuncs.com";
    static readonly AP_SOUTHEAST_5: string = "oss-ap-southeast-5.aliyuncs.com";
    static readonly AP_SOUTHEAST_6: string = "oss-ap-southeast-6.aliyuncs.com";
    static readonly AP_SOUTHEAST_7: string = "oss-ap-southeast-7.aliyuncs.com";
    static readonly EU_CENTRAL_1: string = "oss-eu-central-1.aliyuncs.com";
    static readonly EU_WEST_1: string = "oss-eu-west-1.aliyuncs.com";
    static readonly ME_EAST_1: string = "oss-me-east-1.aliyuncs.com";
    static readonly RG_CHINA_MAINLAND: string = "oss-rg-china-mainland.aliyuncs.com";
  }

  export class PrivateEndpoint {
    static readonly CN_HANGZHOU: string = "oss-cn-hangzhou-internal.aliyuncs.com";
    static readonly CN_SHANGHAI: string = "oss-cn-shanghai-internal.aliyuncs.com";
    static readonly CN_NANJING: string = "oss-cn-nanjing-internal.aliyuncs.com";
    static readonly CN_FUZHOU: string = "oss-cn-fuzhou-internal.aliyuncs.com";
    static readonly CN_WUHAN: string = "oss-cn-wuhan-lr-internal.aliyuncs.com";
    static readonly CN_QINGDAO: string = "oss-cn-qingdao-internal.aliyuncs.com";
    static readonly CN_BEIJING: string = "oss-cn-beijing-internal.aliyuncs.com";
    static readonly CN_ZHANGJIAKOU: string = "oss-cn-zhangjiakou-internal.aliyuncs.com";
    static readonly CN_HUHEHAOTE: string = "oss-cn-huhehaote-internal.aliyuncs.com";
    static readonly CN_WULANCHABU: string = "oss-cn-wulanchabu.aliyuncs-internal.com";
    static readonly CN_SHENZHEN: string = "oss-cn-shenzhen.aliyuncs-internal.com";
    static readonly CN_HEYUAN: string = "oss-cn-heyuan.aliyuncs-internal.com";
    static readonly CN_GUANGZHOU: string = "oss-cn-guangzhou-internal.aliyuncs.com";
    static readonly CN_CHENGDU: string = "oss-cn-chengdu-internal.aliyuncs.com";
    static readonly CN_HONGKONG: string = "oss-cn-hongkong-internal.aliyuncs.com";
    static readonly US_WEST_1: string = "oss-us-west-1-internal.aliyuncs.com";
    static readonly US_EAST_1: string = "oss-us-east-1-internal.aliyuncs.com";
    static readonly AP_NORTHEAST_1: string = "oss-ap-northeast-1-internal.aliyuncs.com";
    static readonly AP_NORTHEAST_2: string = "oss-ap-northeast-2-internal.aliyuncs.com";
    static readonly AP_SOUTHEAST_1: string = "oss-ap-southeast-1-internal.aliyuncs.com";
    static readonly AP_SOUTHEAST_2: string = "oss-ap-southeast-2-internal.aliyuncs.com";
    static readonly AP_SOUTHEAST_3: string = "oss-ap-southeast-3-internal.aliyuncs.com";
    static readonly AP_SOUTHEAST_5: string = "oss-ap-southeast-5-internal.aliyuncs.com";
    static readonly AP_SOUTHEAST_6: string = "oss-ap-southeast-6-internal.aliyuncs.com";
    static readonly AP_SOUTHEAST_7: string = "oss-ap-southeast-7-internal.aliyuncs.com";
    static readonly EU_CENTRAL_1: string = "oss-eu-central-1-internal.aliyuncs.com";
    static readonly EU_WEST_1: string = "oss-eu-west-1.aliyuncs-internal.com";
    static readonly ME_EAST_1: string = "oss-me-east-1-internal.aliyuncs.com";
  }
}


export default DomainConstants;