export class ResponseHeaderOverrides {
  static RESPONSE_HEADER_CONTENT_TYPE = "response-content-type";
  static RESPONSE_HEADER_CONTENT_LANGUAGE = "response-content-language";
  static RESPONSE_HEADER_EXPIRES = "response-expires";
  static RESPONSE_HEADER_CACHE_CONTROL = "response-cache-control";
  static RESPONSE_HEADER_CONTENT_DISPOSITION = "response-content-disposition";
  static RESPONSE_HEADER_CONTENT_ENCODING = "response-content-encoding";
}