export default class HttpHeaders {
  static AUTHORIZATION: string = "Authorization";
  static CACHE_CONTROL: string = "Cache-Control";
  static CONTENT_DISPOSITION: string = "Content-Disposition";
  static CONTENT_ENCODING: string = "Content-Encoding";
  static CONTENT_LENGTH: string = "Content-Length";
  static CONTENT_MD5: string = "Content-MD5";
  static CONTENT_TYPE: string = "Content-Type";
  static TRANSFER_ENCODING: string = "Transfer-Encoding";
  static DATE: string = "Date";
  static ETAG: string = "ETag";
  static EXPIRES: string = "Expires";
  static HOST: string = "Host";
  static LAST_MODIFIED: string = "Last-Modified";
  static RANGE: string = "Range";
  static LOCATION: string = "Location";
  static CONNECTION: string = "Connection";
}